package simulator;

/**
 * The interface defines the method that has to be implemented for all the listeners events 
 * generated by the IndexingProgress object.
 * 
 * @author Alessandro Montalti, Andrea Zagnoli, Marco Santarelli, Matteo Desanti. 
 */
public interface ISimulationProgressListener {
	
	/**
	 * Method called whenever a progress is made during the indexing process of a set of files.
	 * It returns the percentage of the progress
	 * 
	 * @param progress Percentage of the progress
	 */
	public void progressMade(float progress) ;
}
